name: build test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: build (${{ matrix.ros_distro }})
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            container_image: osrf/ros:humble-desktop-jammy
            ubuntu_version: "22.04"
          - ros_distro: jazzy
            container_image: osrf/ros:jazzy-desktop-noble
            ubuntu_version: "24.04"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies of choreonoid
        run: |
          export DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC
          apt-get update && apt-get -y upgrade
          script_url="https://raw.githubusercontent.com/choreonoid/choreonoid/master/misc/script/install-requisites-ubuntu-${{ matrix.ubuntu_version }}.sh"
          curl -sL "$script_url" -o /tmp/install-deps.sh
          sed -i 's/sudo --preserve-env=[^ ]* //' /tmp/install-deps.sh
          sh /tmp/install-deps.sh
          apt-get -y install python3-colcon-coveragepy-result python3-colcon-lcov-result

      - name: Run build test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros_distro }}
          vcs-repo-file-url: dependency.repos
          extra-cmake-args: -DWITH_INTEGRATION_TEST=ON
          # If possible, pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
